# Generated by Django 4.1.7 on 2023-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dBitro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest_master',
            name='blue_pic',
            field=models.ImageField(blank=True, null=True, upload_to='blue icon'),
        ),
        migrations.AddField(
            model_name='interest_master',
            name='grey_pic',
            field=models.ImageField(blank=True, null=True, upload_to='grey icon'),
        ),
        migrations.AddField(
            model_name='pets_master',
            name='blue_pic',
            field=models.ImageField(blank=True, null=True, upload_to='blue icon'),
        ),
        migrations.AddField(
            model_name='pets_master',
            name='grey_pic',
            field=models.ImageField(blank=True, null=True, upload_to='grey icon'),
        ),
    ]
