# Generated by Django 4.1.7 on 2023-05-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dBitro', '0002_interest_master_blue_pic_interest_master_grey_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('city_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dBitro.state_master')),
            ],
        ),
    ]
