def sub1() :
    print("Branch CIVIL\n1st YEAR\nSEM 1\n")
    print("THEORY SUBJECT :")
    print("Mathematics I")
    print("Chemistry")
    print("English for Communication")
    print("Basic Electronics")
    print("Mechanics")
    print("Engineering Drawing and Graphics")
    print("Electrical Technology")
    print("Introduction to Manufacturing Processes")
