def sub2() :
    print("Branch ET\n1st YEAR\nSEM 2\n")
    print("THEORY SUBJECT :")
    print("Seamanship, Elementary Navigation & Survival at Sea")
    print("Mathematics – II")
    print("Applied Thermodynamics – I")
    print("Strength of Materials – I")
    print("Computer Science")
    print("Engineering Mechanics – II")
    print("Engineering & Machine Drawing")
    print("Applied Mechanics Laboratory")
    print("Workshop Practicals – II")
    print("Computer Laboratory – I")
