# Generated by Django 4.1.7 on 2023-07-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_educationmaster_gender_master_icebreak_master_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icebreak_master',
            new_name='GenderMaster',
        ),
        migrations.RenameModel(
            old_name='Gender_master',
            new_name='IcebreakMaster',
        ),
        migrations.RenameModel(
            old_name='Political_master',
            new_name='LanguageMaster',
        ),
        migrations.RenameModel(
            old_name='language_master',
            new_name='PoliticalMaster',
        ),
        migrations.RenameModel(
            old_name='Prompts_master',
            new_name='PromptsMaster',
        ),
        migrations.RenameField(
            model_name='gendermaster',
            old_name='icebreak_name',
            new_name='gender_name',
        ),
        migrations.RenameField(
            model_name='icebreakmaster',
            old_name='gender_name',
            new_name='icebreak_name',
        ),
        migrations.RenameField(
            model_name='languagemaster',
            old_name='political_name',
            new_name='language_name',
        ),
        migrations.RenameField(
            model_name='politicalmaster',
            old_name='language_name',
            new_name='political_name',
        ),
    ]
