# Generated by Django 4.0.6 on 2023-10-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('middle_name', models.CharField(max_length=40, null=True)),
                ('phone_number_country_code', models.CharField(max_length=5, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('i_agree_on_terms_and_conditions', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
