# Generated by Django 4.0.6 on 2023-10-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuth',
        ),
    ]
