# Generated by Django 4.1.7 on 2023-08-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_reviewproductmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewproductmaster',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
