# Generated by Django 4.1.7 on 2023-08-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_productmaster_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='category',
        ),
    ]
