# Generated by Django 4.1.7 on 2023-07-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_icebreak_master_gendermaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('interest_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('blue_pic', models.ImageField(blank=True, null=True, upload_to='Blue Icon')),
                ('grey_pic', models.ImageField(blank=True, null=True, upload_to='Grey Icon')),
            ],
        ),
        migrations.CreateModel(
            name='PetsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('pets_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('blue_pic', models.ImageField(blank=True, null=True, upload_to='Blue Icon')),
                ('grey_pic', models.ImageField(blank=True, null=True, upload_to='Grey Icon')),
            ],
        ),
    ]
