# Generated by Django 4.1.7 on 2023-08-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amenity_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=250, null=True)),
                ('property_discription', models.TextField(blank=True, null=True)),
                ('property_price', models.PositiveIntegerField(blank=True, null=True)),
                ('property_location', models.TextField(blank=True, null=True)),
                ('property_main_image', models.ImageField(blank=True, null=True, upload_to='Property main image')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='Property image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertymaster')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.amenitymaster')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertymaster')),
            ],
        ),
    ]
