# Generated by Django 4.2 on 2023-06-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('das_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor_Profile',
        ),
    ]
