# Generated by Django 4.2 on 2023-06-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('das_admin', '0008_alter_doctorprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='dob',
        ),
    ]
