# Generated by Django 4.1.7 on 2023-07-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('das_admin', '0013_remove_doctorqualification_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoraddress',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
