

# error type 

# 3 types of error


# Syntax Errors (Parsing Errors)
# Runtime Errors (Exceptions)
# Logical Errors (Bugs)



# KeyError: Raised when a key is not found in a dictionary.
# ImportError : Raised when the imported module is not found.
# IndentationError : Raised when there is an incorrect indentation.
# MemoryError : Raised when an operation runs out of memory.
# NameError :It occurs when the variable is not defined.
# SystemError : Raised when the interpreter detects internal error.
# ZeroDivisionError : Raised when we try to divide any number by zero.





# AttributeError : raised when an attribute reference or assignment fails.   
# 
# ex:X = 10
 
# Raises an AttributeError
# X.append(6)



# IndexError : Raised When the wrong index of a list is retrieved.


# TypeError : Raised When the different data types in an operation.

# kid_ages = [2, 7, 5, 6, 3]

# max = 0
# max = max(kid_ages)
# print(max)



# ValueError : Raised when the wrong value is assigned to an object.

# import math

# try:
#     math.sqrt(-100)
# except ValueError:
    # print('Positive number expected for square root operation')
