def sub3() :
    print("Branch AI\n2nd YEAR\nSEM 3\n")
    print("THEORY SUBJECT :")
    print("Computer System Architecture")
    print("Design and Analysis of Algorithms")
    print("Web Technologies")
    print("Functional Programming in Python")
    print("Introduction to the Internet of Things")
    print("Communication WKSP 2.0")
    print("Securing Digital Assets")
    print("Introduction to Applied Psychology")
