# Generated by Django 4.2 on 2023-05-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('country_pic', models.ImageField(blank=True, null=True, upload_to='Country pic')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
