def sub4() :
    print("Branch AI\n2nd YEAR\nSEM 4\n")
    print("THEORY SUBJECT :")
    print("Operating Systems")
    print("Data Communication and Computer Networks")
    print("Introduction to Java and OOPS")
    print("Applied Statistical Analysis (for AI and ML)")
    print("Current Topics in AI and ML")
    print("Database Management Systems & Data Modelling")
    print("Impact of Media on Society")
