# Generated by Django 4.2 on 2023-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_admin', '0006_doctorprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
