# Generated by Django 4.2 on 2023-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_admin', '0007_doctorprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.BooleanField(blank=True, max_length=15, null=True),
        ),
    ]
