# Generated by Django 4.2 on 2023-06-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das_admin', '0011_alter_doctorcontactdetails_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
