# Generated by Django 4.1.7 on 2023-08-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_timestamp_reviewproductmaster_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='Product Main Image'),
        ),
    ]
